"""
pages/6_Gnuplot.py -- Gnuplot Visualization
Generate publication-quality plots from scan data using gnuplot.
Renders via subprocess, displays in Streamlit, exports .gp scripts.
"""
from __future__ import annotations

import os
import shutil
import subprocess
import tempfile

import numpy as np
import streamlit as st

from automation_station.ui.layout import render_header
from harrington_common.theme import aw_panel

st.set_page_config(page_title="Gnuplot", layout="wide")
render_header()

with aw_panel():
    st.subheader("Gnuplot Visualization")
    st.caption("Publication-quality plots from scan data. Edit scripts live. Export .gp + .dat files.")


# ── Check gnuplot is installed ────────────────────────────────────────────────
GNUPLOT_BIN = shutil.which("gnuplot")
if GNUPLOT_BIN is None:
    for candidate in [
        r"C:\Program Files\gnuplot\bin\gnuplot.exe",
        r"C:\Program Files (x86)\gnuplot\bin\gnuplot.exe",
        r"C:\gnuplot\bin\gnuplot.exe",
    ]:
        if os.path.isfile(candidate):
            GNUPLOT_BIN = candidate
            break

if GNUPLOT_BIN is None:
    st.error(
        "**gnuplot not found.** Install from [gnuplot.info](http://www.gnuplot.info/download.html) "
        "and make sure it's on your PATH, or: `winget install gnuplot`"
    )
    st.stop()
else:
    st.sidebar.success(f"gnuplot: `{GNUPLOT_BIN}`")


# ── Check for scan data ──────────────────────────────────────────────────────
fit = st.session_state.get("fit_result")
scan = st.session_state.get("scan_data")

has_caustic = fit is not None and "z_data" in fit
has_raw = scan is not None and len(scan.get("raw", [])) > 0

if not has_caustic:
    st.warning("No scan data available. Run a scan first, then come back here.")
    st.info("You can also paste your own data below to plot with gnuplot.")


# ── Build data files ──────────────────────────────────────────────────────────
def build_caustic_dat(fit_data):
    lines = ["# z_um\tw_um"]
    for z, w in zip(fit_data["z_data"], fit_data["w_data"]):
        lines.append(f"{z:.2f}\t{w:.2f}")
    return "\n".join(lines)


def build_caustic_fit_dat(fit_data):
    lines = ["# z_um\tw_fit_um"]
    for z, w in zip(fit_data["z_fit"], fit_data["w_fit"]):
        lines.append(f"{z:.2f}\t{w:.2f}")
    return "\n".join(lines)


# ── Default gnuplot scripts ──────────────────────────────────────────────────
def default_caustic_script(fit_data):
    w0 = fit_data["w0"]
    z0 = fit_data["z0"]
    M2 = fit_data["M2"]
    return f"""\
# Beam Caustic Plot -- gnuplot
# Generated by automation-station

set terminal pngcairo enhanced font "Arial,12" size 1200,700 \\
    background "#faf8f5"
set output "beam_caustic.png"

# Style (Americana)
set border linecolor rgb "#1a1a2e"
set grid linecolor rgb "#e0dcd6" linewidth 0.5
set key textcolor rgb "#1a1a2e" box linecolor rgb "#e0dcd6"
set title "Beam Caustic -- M^2 = {M2:.2f}, w_0 = {w0:.1f} um" \\
    textcolor rgb "#1a3a5c" font "Arial,16"
set xlabel "Z position (um)" textcolor rgb "#1a1a2e" font "Arial,13"
set ylabel "Beam radius (um)" textcolor rgb "#1a1a2e" font "Arial,13"
set tics textcolor rgb "#5c5c6e"

# Waist markers
set arrow from {z0:.1f}, graph 0 to {z0:.1f}, graph 1 nohead \\
    linecolor rgb "#5c5c6e" dashtype 3 linewidth 1
set arrow from graph 0, first {w0:.1f} to graph 1, first {w0:.1f} nohead \\
    linecolor rgb "#b8860b" dashtype 2 linewidth 1
set arrow from graph 0, first -{w0:.1f} to graph 1, first -{w0:.1f} nohead \\
    linecolor rgb "#b8860b" dashtype 2 linewidth 1
set label "w_0 = {w0:.1f} um" at graph 0.02, first {w0:.1f}*1.15 \\
    textcolor rgb "#b8860b" font "Arial,10"

# Plot data + fit (mirrored +/-w)
plot "caustic_data.dat" using 1:2 with points \\
        pointtype 7 pointsize 1.2 linecolor rgb "#8b2332" title "Data", \\
     "caustic_data.dat" using 1:(-$2) with points \\
        pointtype 7 pointsize 1.2 linecolor rgb "#8b2332" notitle, \\
     "caustic_fit.dat" using 1:2 with lines \\
        linewidth 2.5 linecolor rgb "#1a3a5c" title "Fit", \\
     "caustic_fit.dat" using 1:(-$2) with lines \\
        linewidth 2.5 linecolor rgb "#1a3a5c" notitle
"""


CUSTOM_DATA_SCRIPT = """\
# Custom gnuplot script
# Paste your data below between the markers, or load from a file.

set terminal pngcairo enhanced font "Arial,12" size 1200,700 \\
    background "#faf8f5"
set output "custom_plot.png"

set border linecolor rgb "#1a1a2e"
set grid linecolor rgb "#e0dcd6"
set key textcolor rgb "#1a1a2e"
set xlabel "X" textcolor rgb "#1a1a2e"
set ylabel "Y" textcolor rgb "#1a1a2e"
set tics textcolor rgb "#5c5c6e"

# Inline data example
$DATA << EOD
1  1.0
2  4.0
3  9.0
4  16.0
5  25.0
EOD

plot $DATA using 1:2 with linespoints \\
    pointtype 7 linecolor rgb "#8b2332" title "Sample"
"""


# ── Run gnuplot ───────────────────────────────────────────────────────────────
def run_gnuplot(script, data_files=None):
    """Execute a gnuplot script, return (success, png_bytes, stderr)."""
    with tempfile.TemporaryDirectory() as tmpdir:
        if data_files:
            for fname, content in data_files.items():
                with open(os.path.join(tmpdir, fname), "w") as f:
                    f.write(content)

        gp_path = os.path.join(tmpdir, "plot.gp")
        with open(gp_path, "w") as f:
            f.write(script)

        result = subprocess.run(
            [GNUPLOT_BIN, gp_path],
            cwd=tmpdir,
            capture_output=True,
            timeout=15,
        )

        png_bytes = None
        for fname in os.listdir(tmpdir):
            if fname.endswith(".png"):
                with open(os.path.join(tmpdir, fname), "rb") as f:
                    png_bytes = f.read()
                break

        return (
            result.returncode == 0,
            png_bytes,
            result.stderr.decode("utf-8", errors="replace"),
        )


# ── Tabs ──────────────────────────────────────────────────────────────────────
if has_caustic:
    tab1, tab2 = st.tabs(["Beam Caustic", "Custom Script"])
else:
    tab2 = st.container()
    tab1 = None

# ── TAB 1: Beam Caustic ──────────────────────────────────────────────────────
if tab1 is not None and has_caustic:
    with tab1:
        with aw_panel():
            st.markdown("#### Beam Caustic -- gnuplot")
            st.markdown("Edit the script below, then click **Render** to generate the plot.")

            col_left, col_right = st.columns([1, 1])

            with col_left:
                default_script = default_caustic_script(fit)
                script = st.text_area(
                    "gnuplot script", value=default_script, height=500,
                    key="gp_caustic_script",
                )

                col_r, col_d1, col_d2, col_d3 = st.columns(4)
                with col_r:
                    render_caustic = st.button(
                        "Render", type="primary", key="render_caustic",
                        use_container_width=True,
                    )
                with col_d1:
                    st.download_button(
                        "Download .gp", script, "beam_caustic.gp", "text/plain",
                        use_container_width=True,
                    )
                with col_d2:
                    dat = build_caustic_dat(fit)
                    st.download_button(
                        "Download data.dat", dat, "caustic_data.dat", "text/plain",
                        use_container_width=True,
                    )
                with col_d3:
                    fit_dat = build_caustic_fit_dat(fit)
                    st.download_button(
                        "Download fit.dat", fit_dat, "caustic_fit.dat", "text/plain",
                        use_container_width=True,
                    )

            with col_right:
                if render_caustic:
                    data_files = {
                        "caustic_data.dat": build_caustic_dat(fit),
                        "caustic_fit.dat": build_caustic_fit_dat(fit),
                    }
                    ok, png, stderr = run_gnuplot(script, data_files)
                    if ok and png:
                        st.image(png, caption="beam_caustic.png", use_container_width=True)
                        st.download_button(
                            "Download PNG", png, "beam_caustic.png", "image/png",
                            key="dl_caustic_png", use_container_width=True,
                        )
                    else:
                        st.error("gnuplot failed:")
                        st.code(stderr, language="text")
                else:
                    st.info("Click **Render** to generate the plot.")

                with st.expander("Data preview"):
                    st.code(build_caustic_dat(fit), language="text")

# ── TAB 2 / Custom Script ────────────────────────────────────────────────────
with (tab2 if tab1 is not None else tab2):
    with aw_panel():
        if tab1 is not None:
            st.markdown("#### Custom gnuplot Script")
        else:
            st.markdown("#### gnuplot Script Editor")

        st.markdown(
            "Write any gnuplot script. Use `$DATA << EOD ... EOD` for inline data, "
            "or reference files you upload below."
        )

        col_left, col_right = st.columns([1, 1])

        with col_left:
            custom_script = st.text_area(
                "gnuplot script", value=CUSTOM_DATA_SCRIPT, height=500,
                key="gp_custom_script",
            )

            uploaded_files = st.file_uploader(
                "Upload data files (referenced in your script)",
                accept_multiple_files=True, key="gp_uploads",
            )

            col_r, col_d = st.columns(2)
            with col_r:
                render_custom = st.button(
                    "Render", type="primary", key="render_custom",
                    use_container_width=True,
                )
            with col_d:
                st.download_button(
                    "Download .gp", custom_script, "custom_plot.gp", "text/plain",
                    key="dl_custom_gp", use_container_width=True,
                )

        with col_right:
            if render_custom:
                data_files = {}
                if uploaded_files:
                    for uf in uploaded_files:
                        data_files[uf.name] = uf.getvalue().decode("utf-8", errors="replace")
                if has_caustic:
                    data_files["caustic_data.dat"] = build_caustic_dat(fit)
                    data_files["caustic_fit.dat"] = build_caustic_fit_dat(fit)

                ok, png, stderr = run_gnuplot(custom_script, data_files)
                if ok and png:
                    st.image(png, caption="custom_plot.png", use_container_width=True)
                    st.download_button(
                        "Download PNG", png, "custom_plot.png", "image/png",
                        key="dl_custom_png", use_container_width=True,
                    )
                else:
                    st.error("gnuplot failed:")
                    st.code(stderr, language="text")
            else:
                st.info("Click **Render** to generate the plot.")

# ── Sidebar help ──────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("#### gnuplot Quick Reference")
    st.markdown("""
    **Terminals:** `pngcairo`, `svg`, `pdfcairo`

    **Common:** `set xlabel`, `set ylabel`, `set title`, `set grid`, `set key`

    **Styles:** `with lines`, `with points`, `with linespoints`, `with boxes`

    **Inline data:** `$DATA << EOD ... EOD`

    **Fitting:** `f(x) = a*x + b` then `fit f(x) "data.dat" via a, b`
    """)
